# ????
server:
  port: 8080 # ????
  servlet:
    jsp:
      init-parameters:
        development: true # ??JSP???????JSP????
    context-path: /ssm # ?????
# ?????
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db9?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false
  mvc:
    view:
      prefix: /WEB-INF/page/ # ????
      suffix: .jsp # ????
    static-path-pattern: /**
    hiddenmethod:
      filter:
        enabled: true
# Mybatis??
mybatis:
  mapper-locations: classpath:mapper/*.xml # Mapper XML ????
  type-aliases-package: com.dj.ssm.pojo # ?????
  configuration:
    map-underscore-to-camel-case: true # ????
#??
logging:
  level:
    com.dj.ssm.mapper: debug


